// src/lib/components/ImageDialog.svelte
<script lang="ts">
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import { AspectRatio } from "./ui/aspect-ratio";

  let { isOpen, story } = $props();
  const { thumbnail, media, mediaType } = story;
</script>

<Dialog.Root open={isOpen} on:close={() => (isOpen = false)}>
  <Dialog.Content class="p-0">
    <AspectRatio ratio={9 / 16}>
      {#if mediaType === "photo"}
        <img src={thumbnail} alt="story" class="w-full object-cover" />
      {:else}
        <video controls autoplay class="w-full object-cover">
          <source src={media} type="video/mp4" />
          Your browser does not support the video tag.
          <track kind="captions" />
        </video>
      {/if}
    </AspectRatio>
  </Dialog.Content>
</Dialog.Root>

// src/components/ImageDialog.tsx
import React, { Dispatch } from "react";
import { Dialog, DialogContent } from "./ui/dialog";
import Image from "next/image";
import { AspectRatio } from "./ui/aspect-ratio";

interface Props {
  isOpen: boolean;
  setIsOpen: Dispatch<React.SetStateAction<boolean>>;
  isVideo?: boolean;
  src: string;
}

const ImageDialog = (props: Props) => {
  const { isOpen, setIsOpen, isVideo, src } = props;
  return (
    <Dialog open={isOpen} modal onOpenChange={setIsOpen}>
      <DialogContent className="pt-12 max-w-[80%] sm:max-w-lg">
        <AspectRatio ratio={9 / 16}>
          {isVideo ? (
            <video controls className="w-full">
              <source src={src} type="video/mp4" />
              Your browser does not support the video tag.
            </video>
          ) : (
            <Image
              src={src}
              alt="Story"
              className="w-full object-cover"
              fill={true}
            />
          )}
        </AspectRatio>
      </DialogContent>
    </Dialog>
  );
};

export default ImageDialog;
