// src/lib/components/Search.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { Button } from "$lib/components/ui/button";
  import { Input } from "$lib/components/ui/input";
  import Search from "lucide-svelte/icons/search";
  import LoaderCircle from "lucide-svelte/icons/loader-circle";
  import { sanitizeUsername, saveUsernameInLocalStorage } from "$lib/utils";

  let username = $state("");
  let isLoading = $state(false);

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    isLoading = true;
    const sanitizedUsername = sanitizeUsername(username);

    if (!sanitizedUsername) {
      // TODO: show error message
      return;
    }

    saveUsernameInLocalStorage(sanitizedUsername);

    await goto(`/${sanitizedUsername}`);
  }
</script>

<form onsubmit={handleSubmit} class="flex gap-2">
  <Input
    bind:value={username}
    placeholder="Username or URL"
    class="flex-1 focus-visible:ring-0"
    type="text"
    required
    autofocus
    autocomplete="off"
    disabled={isLoading}
  />
  <Button type="submit" size="icon" disabled={isLoading}>
    {#if isLoading}
      <LoaderCircle class="animate-spin" />
    {:else}
      <Search />
    {/if}
  </Button>
</form>

// src/components/Search.tsx
"use client";
import React, { useState } from "react";
import { Input } from "./ui/input";
import { Button } from "./ui/button";
import { Search as SearchIcon } from "lucide-react";
import { useRouter } from "next/navigation";
import { useAutoAnimate } from "@formkit/auto-animate/react";

const Search = () => {
  const [username, setUSername] = useState("");
  const [error, setError] = useState<string>();
  const [parent] = useAutoAnimate({ duration: 100 });

  const router = useRouter();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    setError("");
    if (!username) {
      setError("Username is required");
    }

    router.push(`/${username}`);
  };

  return (
    <div className="flex flex-col" ref={parent}>
      <form onSubmit={handleSubmit} className="flex gap-2 w-full items-center">
        <Input
          placeholder="Username"
          value={username}
          onChange={e => setUSername(e.target.value)}
          className="text-black"
        />
        <Button type="submit" size="icon" variant="default">
          <SearchIcon />
        </Button>
      </form>
      {error && <p className="text-red-500 text-sm mt-2 pl-1">{error}</p>}
    </div>
  );
};

export default Search;
