// src/components/UserInfo.tsx
import React from "react";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
import { User } from "../types/User.types";
import { getImageUrl } from "@/lib/utils";

interface Props {
  user: User;
}

const formatNumber = (num: number) => {
  return new Intl.NumberFormat().format(num);
};

const UserInfo = async (props: Props) => {
  const { user } = props;

  const { full_name, media_count, hd_profile_pic_versions } = user;
  const { follower_count, following_count, biography } = user;
  const { url, url_signature } = hd_profile_pic_versions[0];
  const image = getImageUrl({ url, url_signature });

  return (
    <div className="flex gap-4">
      <Avatar className="w-[80px] h-[80px]">
        <AvatarImage src={image} alt="profile pic" />
        <AvatarFallback className="text-black">{full_name[0]}</AvatarFallback>
      </Avatar>
      <div className="flex-1 flex flex-col gap-2">
        <div className="flex gap-2 flex-wrap">
          <div className="flex gap-1">
            <span className="font-bold">{formatNumber(media_count)}</span>Posts
          </div>
          <div className="flex gap-1">
            <span className="font-bold">{formatNumber(follower_count)}</span>
            Followers
          </div>
          <div className="flex gap-1">
            <span className="font-bold">{formatNumber(following_count)}</span>
            Following
          </div>
        </div>
        {/* TODO: Poner de un color diferente el nombre */}
        <p className="text-lg">{full_name}</p>
        <p>{biography}</p>
      </div>
    </div>
  );
};

export default UserInfo;

// src/lib/components/UserInfo.svelte
<script lang="ts">
  import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
  import * as Dialog from "$lib/components/ui/dialog/index.js";

  let { userInfo } = $props();
  const { username, profile_pic_url, bio } = userInfo;
  const { follower_count, following_count, media_count } = userInfo;
  const { raw_text: biography } = bio;
  let isOpen = $state(false);

  const formatNumber = (num: number) => {
    return new Intl.NumberFormat().format(num);
  };
</script>

<div class="flex gap-4">
  <Dialog.Root>
    <Dialog.Trigger class="focus-visible:outline-none">
      <Avatar class="w-[80px] h-[80px]">
        <AvatarImage src={profile_pic_url} alt="profile pic" />
        <AvatarFallback class="text-black">{username[0]}</AvatarFallback>
      </Avatar>
    </Dialog.Trigger>
    <Dialog.Content class="p-0">
      <img
        src={profile_pic_url}
        alt="profile pic"
        class="w-full object-cover"
      />
    </Dialog.Content>
  </Dialog.Root>
  <div class="flex-1 flex flex-col gap-2">
    <div class="flex gap-2 flex-wrap">
      <div class="flex gap-1">
        <span class="font-bold">{formatNumber(media_count)}</span>Posts
      </div>
      <div class="flex gap-1">
        <span class="font-bold">{formatNumber(follower_count)}</span>
        Followers
      </div>
      <div class="flex gap-1">
        <span class="font-bold">{formatNumber(following_count)}</span>
        Following
      </div>
    </div>
    <p>{biography}</p>
  </div>
</div>
